// build_data.mjs — dev-only. Converts the two connector CSVs into an ES module
// (connectors_data.js) that the static page imports. NOT shipped to users; re-run
// whenever the CSVs change:  node deutsch/build_data.mjs
//
// Output: deutsch/connectors_data.js exporting { CONNECTORS, SENTENCES }.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));

// --- minimal RFC-4180-ish CSV parser (handles quoted fields, commas, quotes) ----
function parseCsv(text) {
  const rows = [];
  let row = [];
  let field = '';
  let inQuotes = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (inQuotes) {
      if (c === '"') {
        if (text[i + 1] === '"') { field += '"'; i++; }
        else inQuotes = false;
      } else field += c;
    } else if (c === '"') {
      inQuotes = true;
    } else if (c === ',') {
      row.push(field); field = '';
    } else if (c === '\n' || c === '\r') {
      if (c === '\r' && text[i + 1] === '\n') i++;
      row.push(field); field = '';
      if (row.length > 1 || row[0] !== '') rows.push(row);
      row = [];
    } else field += c;
  }
  if (field !== '' || row.length) { row.push(field); rows.push(row); }
  return rows;
}

function toObjects(rows) {
  const [header, ...body] = rows;
  return body
    .filter((r) => r.some((c) => c.trim() !== ''))
    .map((r) => Object.fromEntries(header.map((h, i) => [h.trim(), (r[i] ?? '').trim()])));
}

// --- map English metadata labels to short German UI labels ----------------------
const TYPE_DE = {
  Conjunction: 'Konjunktion',
  'Subordinating Conjunction': 'Subjunktion',
  'Paired Conjunction': 'Paarkonjunktion',
  'Conjunctive Adverb': 'Konjunktionaladverb',
};
const CATEGORY_DE = {
  Addition: 'Aufzählung',
  Contrast: 'Gegensatz',
  Reason: 'Grund',
  Alternative: 'Alternative',
  'Condition / Time': 'Bedingung / Zeit',
  Time: 'Zeit',
  'Time / Contrast': 'Zeit / Gegensatz',
  'Time / Condition': 'Zeit / Bedingung',
  'Time / Conclusion': 'Zeit / Schluss',
  Condition: 'Bedingung',
  'Condition / Alternative': 'Bedingung / Alternative',
  Complement: 'Ergänzung (dass/ob)',
  'Indirect Question': 'Indirekte Frage',
  Purpose: 'Zweck',
  'Negative Addition': 'Aufzählung (verneint)',
  'Reason / Consequence': 'Grund / Folge',
};

function countStars(s) {
  return (s.match(/★/g) || []).length;
}

// --- build CONNECTORS from level1 ----------------------------------------------
const l1 = toObjects(parseCsv(readFileSync(join(here, 'german_connectors_level1.csv'), 'utf8')));
const connectors = l1.map((r) => ({
  id: r['ID'],
  word: r['German connector'],
  meaning: r['English meaning'],
  type: TYPE_DE[r['Type']] || r['Type'],
  category: CATEGORY_DE[r['Category']] || r['Category'],
  wordOrder: r['Word order rule'],
  cefr: r['CEFR estimate'],
  zapStars: countStars(r['ZAP importance']),
  gapCount: parseInt(r['Gap count'], 10) || 1,
  confusedWith: (r['Commonly confused with'] || '')
    .split('/')
    .map((s) => s.trim())
    .filter(Boolean),
}));
const connectorById = new Map(connectors.map((c) => [c.id, c]));

// --- build SENTENCES from level2 -----------------------------------------------
const l2 = toObjects(parseCsv(readFileSync(join(here, 'german_connectors_exercises_level2.csv'), 'utf8')));

// split "a / b / c" alternatives; strip the "..." join marker from paired forms
function splitAlts(s) {
  return (s || '')
    .split('/')
    .map((x) => x.replace(/\s*\.\.\.\s*/g, ' ').replace(/\s+/g, ' ').trim())
    .filter(Boolean);
}

const sentences = l2.map((r) => {
  const id = r['Connector ID'];
  const conn = connectorById.get(id);
  const gapSentence = r['Gap sentence'];
  const gapCount = (gapSentence.match(/_{2,}/g) || []).length || conn?.gapCount || 1;

  // accepted = correct answer + accepted alternatives, all in this sentence's context
  const correct = (r['Correct answer'] || '').replace(/\s*\.\.\.\s*/g, ' ').replace(/\s+/g, ' ').trim();
  const alts = splitAlts(r['Accepted alternatives']);
  const accepted = [...new Set([correct, ...alts].filter(Boolean))];

  return {
    connectorId: id,
    word: conn?.word || correct,
    category: conn?.category || '',
    type: conn?.type || '',
    gapSentence,
    fullSentence: r['Full sentence'],
    accepted,
    gapCount,
    context: r['Context'] || '',
    difficulty: r['Difficulty'] || '',
    skill: r['Tested skill'] || '',
    altNotes: r['Alternative notes'] || '',
  };
});

// --- emit ----------------------------------------------------------------------
const out =
  '// GENERATED by build_data.mjs from the connector CSVs. Do not edit by hand.\n' +
  '// Re-run:  node deutsch/build_data.mjs\n\n' +
  'export const CONNECTORS = ' + JSON.stringify(connectors, null, 2) + ';\n\n' +
  'export const SENTENCES = ' + JSON.stringify(sentences, null, 2) + ';\n';

writeFileSync(join(here, 'connectors_data.js'), out);

// summary to stdout
const perConn = {};
for (const s of sentences) perConn[s.connectorId] = (perConn[s.connectorId] || 0) + 1;
console.log(`Connectors: ${connectors.length}`);
console.log(`Sentences:  ${sentences.length} (covering ${Object.keys(perConn).length} connectors)`);
console.log('Per connector:', JSON.stringify(perConn));
const cats = [...new Set(connectors.map((c) => c.category))].sort();
console.log('Categories:', cats.join(' · '));
